# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessGame', '0002_roominfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField()),
                ('room_number', models.IntegerField(default=0)),
            ],
        ),
    ]
