# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessGame', '0003_chessboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='roominfo',
            name='full',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='user1',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='user2',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
