# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessGame', '0004_auto_20160607_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboard',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
