# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessGame', '0005_auto_20160607_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='stay',
            field=models.IntegerField(default=0),
        ),
    ]
