# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessGame', '0006_roominfo_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='turn1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roominfo',
            name='turn2',
            field=models.IntegerField(default=0),
        ),
    ]
