# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessGame', '0007_auto_20160607_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfo',
            name='turn1',
        ),
        migrations.RemoveField(
            model_name='roominfo',
            name='turn2',
        ),
    ]
